services:
    db:
        image: postgres:17
        container_name: employee_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: employee_management
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - employee_network

    backend:
        build: ./backend/Backend
        container_name: employee_backend
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: admin
            DB_PASSWORD: admin123
            DB_NAME: employee_management
            BACKEND_PORT: 5058
            ASPNETCORE_URLS: http://+:5058
        depends_on:
            - db
        networks:
            - employee_network
        ports:
            - "5058:5058"

    frontend:
        build: ./frontend
        container_name: employee_frontend
        depends_on:
            - backend
        networks:
            - employee_network
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"

volumes:
    pgdata:

networks:
    employee_network:
        driver: bridge
