import { Employee } from '../interfaces/employee.interface';

export const EMPLOYEES_MOCK: Employee[] = [
  {
    id: 1,
    name: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    documentCode: '123456789',
    managerName: 'Alice Johnson',
    birthDate: new Date(1990, 5, 15),
  },
  {
    id: 2,
    name: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    documentCode: '987654321',
    managerName: 'Bob Williams',
    birthDate: new Date(1985, 10, 20),
  },
  {
    id: 3,
    name: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@example.com',
    documentCode: '112233445',
    birthDate: new Date(1992, 3, 5),
  },
  {
    id: 4,
    name: 'Emily',
    lastName: 'Clark',
    email: 'emily.clark@example.com',
    documentCode: '223344556',
    managerName: 'David Miller',
    birthDate: new Date(1988, 7, 12),
  },
  {
    id: 5,
    name: 'Robert',
    lastName: 'Johnson',
    email: 'robert.johnson@example.com',
    documentCode: '334455667',
    birthDate: new Date(1995, 1, 25),
  },
  {
    id: 6,
    name: 'Sophia',
    lastName: 'Williams',
    email: 'sophia.williams@example.com',
    documentCode: '445566778',
    managerName: 'Emma Davis',
    birthDate: new Date(1993, 9, 30),
  },
  {
    id: 7,
    name: 'William',
    lastName: 'Davis',
    email: 'william.davis@example.com',
    documentCode: '556677889',
    birthDate: new Date(1991, 4, 18),
  },
  {
    id: 8,
    name: 'Olivia',
    lastName: 'Martinez',
    email: 'olivia.martinez@example.com',
    documentCode: '667788990',
    managerName: 'Michael Brown',
    birthDate: new Date(1987, 2, 8),
  },
  {
    id: 9,
    name: 'James',
    lastName: 'Taylor',
    email: 'james.taylor@example.com',
    documentCode: '778899001',
    birthDate: new Date(1994, 11, 22),
  },
  {
    id: 10,
    name: 'Emma',
    lastName: 'Moore',
    email: 'emma.moore@example.com',
    documentCode: '889900112',
    managerName: 'Sophia Williams',
    birthDate: new Date(1989, 6, 14),
  },
];
